global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9090']
      
  - job_name: 'node_exporter'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9100']

   - job_name: 'grafana'
     scrape_interval: 5s
     static_configs:
       - targets: ['192.168.2.200:9100']

   - job_name: 'hosta'
     scrape_interval: 5s
     static_configs:
       - targets: ['192.168.2.210:9100']